### ISSUE TITLE
Have Issue on merging pe+ files.

### ISSUE THREAD

**Issue by KidoPlay** [jnastarot/shibari#1]
Please test.
Haven't figured out which part go wrong yet.

**Comment by KidoPlay** [comment]
Seems that IAT is not correctly filled in the right place.

Still debugging the code to find out why.

**Comment by jnastarot** [comment]
you can send me files with configs which you process?

**Comment by KidoPlay** [comment]
> you can send me files with configs which you process?

Of course.
Here is the sample files.
[Release.zip](https://github.com/jnastarot/shibari/files/2897795/Release.zip)
The configs I use is pretty simple

`.\shibari_console.exe module=Target.exe module=DummyDll.dll extname=user32.dll`
After which, it will generate a 'shibari_result.exe'. 
[shibari_result.zip](https://github.com/jnastarot/shibari/files/2897798/shibari_result.zip)
Its IAT is empty for some reason.

Thanks

**Comment by jnastarot** [comment]
The problem is in the internals of the CRT, 
the CRT is initialized incorrectly because of this function as cout does not work.
Use printf to output text from a dll, 
but mixing printf and CRT functions can cause undefined behavior.

**Comment by jnastarot** [comment]
sorry it's my mistake ;)
the problem is that in the compilation debug there is a link to the data in the import and all imports are processed by default as functions so a redirect to the new IAT is created
function what trying to read data by imported ptr is reading a redirection code
