### ISSUE TITLE
have issue on add imports.

### ISSUE THREAD

**Issue by iunsped** [jnastarot/shibari#2]
my english is very bad,please.
in x64 mode,i only added an import ,did not merging pe.
old:
sub rsp,28
mov rcx,qword ptr ds:[<&?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A>] //mov rcx, qword ptr ds:[0x000000013F8E20B0]
call <x64.std::operator<<<std::char_traits<char> >>
xor eax,eax
add rsp,28
ret 

new
sub rsp,28
mov rcx,qword ptr ds:[13F8620B0]
call zzz_x64.13F861020
xor eax,eax
add rsp,28
ret 

all call [import] is error!

In x86 mode, these are all relocated
In x64 mode, ff 15 is all [eip - import - 6]
So I don't know how to deal with this.

old import:
000000013F8E2000  0000000077B620C0  kernel32.GetModuleHandleW
000000013F8E2008  0000000077B8BAB0  kernel32.RtlLookupFunctionEntry
000000013F8E2010  0000000077B8BA50  kernel32.RtlVirtualUnwind
000000013F8E2018  0000000077BDBAB0  kernel32.UnhandledExceptionFilter
000000013F8E2020  0000000077B59020  kernel32.SetUnhandledExceptionFilter
000000013F8E2028  0000000077B55190  kernel32.GetCurrentProcess
000000013F8E2030  0000000077B8C140  kernel32.TerminateProcess
000000013F8E2038  0000000077B8D0D0  kernel32.IsProcessorFeaturePresent
000000013F8E2040  0000000077B559A0  kernel32.QueryPerformanceCounter
new:
000000013F8662D8  0000000077B620C0  kernel32.GetModuleHandleW
000000013F8662E0  0000000077B8BAB0  kernel32.RtlLookupFunctionEntry
000000013F8662E8  0000000077B8BA50  kernel32.RtlVirtualUnwind
000000013F8662F0  0000000077BDBAB0  kernel32.UnhandledExceptionFilter
000000013F8662F8  0000000077B59020  kernel32.SetUnhandledExceptionFilter
000000013F866300  0000000077B55190  kernel32.GetCurrentProcess
000000013F866308  0000000077B8C140  kernel32.TerminateProcess

**Comment by jnastarot** [comment]
can you send me full project with incorrect result?
if you want only add import, you could use only PE library (enma_pe)

**Comment by iunsped** [comment]
Ok! I will study it carefully (enma-pe)
X64 mode Adding an import table cannot change the address of the original import table
Similar to call qword[xxxx] This does not appear in the relocation table. He uses an offset to locate. Ps (my understanding, please don't laugh at me, I don't know PE very well) for translate.google

**Comment by jnastarot** [comment]
yes in x64 code doesnt use relocation for access to the import table , it use RIP relocations what posible only in x64 mode.
so when i move linked import table i replace items of the old import table on thunks what redirect code flow on correct imported api in resulted linked table.
if you stil have a problem with your project just send me part of code  that adding the import.
And do not worry about if you do not understand something, everything comes with practice :octocat:
